### ISSUE TITLE
Android Build Failed to activate the Bitrise Apple Developer Portal connection

### ISSUE THREAD

**Issue by zekapp** [bitrise-steplib/steps-fastlane#44]
I am having below error for version 4.2

Ensure cookies for Apple Developer Portal
Failed to activate the Bitrise Apple Developer Portal connection: %!s(MISSING)
Read more: https://devcenter.bitrise.io/getting-started/signing-up/connecting-apple-dev-account/
errors:
Falied to fetch portal data from Bitrise, error: Response status: 404 - Body: {"error_msg":"No Apple developer account found for this build."}

**Comment by fehersanyi-bitrise** [comment]
Hello there, 
Could you please send us the url of the latest build with this error, so we could check the full logs for some more details? 🙃

**Comment by zekapp** [comment]
Hi Fehersanyi

Here is the link. 

https://app.bitrise.io/build/ed8dacc160341cfa

**Comment by fehersanyi-bitrise** [comment]
So there are a few questions, did you connect your apple developer account to bitrise, also on the team tab of the app you should set up a service credencial user (You I guess) and you should provide the apple dev account password and appspecific password to fastlane so it can go through the 2fa.
also, are You sure that this is an android build? 🤔

**Comment by zekapp** [comment]
Thanks for quick reply.
Here is my answers
1-  I don't have apple developer account. 
2- On the team tab it says "Always the owner" as service credential user. I can see my name on the list but account belongs to corporate account. So I didn't change it.
3- yes it is for android build :)

It works perfect when I switch the version 2.3.13

**Comment by bitce** [comment]
Hi @zekapp!

The service credential user shouldn't be related to these issues, however, you do need an Apple Developer Portal account in order to connect to Apple Developer Portal.

The other issue in the build was due to the Jcenter outage, your build wasn't able to download the dependencies. (https://status.bintray.com/) 

We are a bit confused on what exactly it is that you are trying to accomplish, Is this a purely android build? If so, why would you want to connect to the Developer Portal in the first place?

**Comment by zekapp** [comment]
Yes it is a purely android build. I use fastlane to build and deploy for PlayStore/Hockey app etc. I haven't need to connect to Developer Portal so far.

**Comment by bitce** [comment]
Can you explain to us that what was the issue which for you've opened this issue thread? As both your title and description leads us to believe otherwise

**Comment by bitce** [comment]
I'd suggest checking your fastlane lane, as it definitely tries to make this connection

**Comment by bitce** [comment]
Hi @zekapp4! 

Just an update: this warning was present by an error from us, due to a modification in the Fastlane step. Sorry for the inconvenience!

The reason your build failed was the jcenter issue mentioned earlier, so you should be all right now, let us know if you experience this otherwise!

**Comment by DerLobi** [comment]
Is it possible to make the `Ensure cookies for Apple Developer Portal` step optional? For example only if an apple account is connected.

2FA is only required for the account with the "Account Holder" role (see https://developer.apple.com/support/account/authentication/)
We just use a separate account with the "Developer" and "App Manager" roles and we don't need 2FA for that.

I also had a build failing for unrelated reasons but this log message threw me off.

**Comment by bitce** [comment]
@DerLobi, We're really sorry about the inconvenience! Our tooling team is working on hiding this message and only exposing it when it's relevant it's just proven to be more complicated than expected. But it's in the works!

**Comment by labrador116** [comment]
Hello! I have the same problem for an Android project.
Plugin version: 2.4.0
Error message:
Falied to fetch portal data from Bitrise, error: Response status: 404 - Body: {"error_msg":"No Apple developer account found for this build."}
Command failed, error: exit status 20

Plugin version: 2.3.13
Command failed, error: exit status 20

How can I resolve this problem?

**Comment by bitce** [comment]
Hi @labrador116! As mentioned in this thread above, this is a warning printed out as a bug in the step at the moment. 

We're sorry for the inconvenience, but you can not / do not have to resolve this because this doesn't cause your builds to fail and have virtually no effect on them.

**Comment by labrador116** [comment]
@bitce Hello! My builds are failing. How I can to get the reason for the crash. 
There is "Command failed, error: exit status 20" in the log.

The same build is working stable in a local machine.

**Comment by bitce** [comment]
@labrador116 Can you either open a separate issue thread on https://discuss.bitrise.io/c/issues or simply contact us on our on-site chat about it please?

**Comment by ssuchanowski** [comment]
What's the status here?

BTW https://devcenter.bitrise.io/getting-started/signing-up/connecting-apple-dev-account/ returns `404`.

**Comment by bitce** [comment]
Hi @ssuchanowski! This would be the correct link by now: https://devcenter.bitrise.io/getting-started/connecting-apple-dev-account/ - sorry about that and thanks for bringing this to our attention!

**Comment by notjosh** [comment]
> Hi @labrador116! As mentioned in this thread above, this is a warning printed out as a bug in the step at the moment.

I was getting an _error_ in my Android builds. I hadn't configured anything for Apple (as far as I knew?).

---

For anyone still dealing with this issue, here's what worked for me.

In the "Teams" tab, my selected option for "Apple Developer Portal Account" was a blank row (not sure if that's a bug), but I had to explicitly choose: "No user with connected Apple Developer Portal Account".

<img width="722" alt="image" src="https://user-images.githubusercontent.com/33126/59884656-d671a080-936d-11e9-96ae-cb692a0e870c.png">

Hope that helps!

**Comment by bitce** [comment]
Hi @notjosh! Thanks for sharing this, I'd like to still re-iterate that this is something the Fastlane step prints out regardless of platform type at the moment. Consider this a cosmetic bug. This does not affect your builds, you may get confused about the warning - which is understandable, in this instance please let me know and I'll help you point out the actual error, but this does not fail any builds.

**Comment by ssuchanowski** [comment]
Yeah, I had my issue below this - but because this **warning** was print out in red I was not paying attention.

**Comment by notjosh** [comment]
Hiya @bitce! Warning or not, my build was failing immediately following that output, and was fixed by updating the "Apple Developer Portal Account" setting.

Previously it was a blank entry, which I hadn't previously configured at all - a bad default setting? Invalid state? The blank option is no longer there now that I've changed the value (as per the above screenshot).

---

Digging into it a little more on another project, it has the buggy state still set as the default for that value (again, to clarify: I had never touched this setting previously):

<img width="726" alt="image" src="https://user-images.githubusercontent.com/33126/59941481-243fe480-9412-11e9-938e-7e8f55475b48.png">

Hope that helps clarify that there's actually a bug in there somewhat related to the message!

**Comment by bitce** [comment]
Hi @notjosh!

Could you include the mentioned builds? :) What you detail about the blank option sounds interesting, although, more like a website bug than something in the step.

Didn't mean to write this off this is indeed a bug, I believe I specifically confirmed this earlier. 

The situation is that our Tooling team intended to print this warning out in the Fastlane steps - in case you would like to connect to the Developer Portal Account from your fastlane manually, instead of our own solutions, (the step that would print this out and needs this setting is the Auto Provision step, also using fastlane) so people could understand what would be wrong in that instance. Unfortuantely this didn't prove to be that easy (the task is ongoing still) and the result is now that this is printed out in every fastlane step. 

We all agree that this warning is confusing and this isn't ideal and to deal with this is still on the table, hope that is clear to everyone! The team just would like to focus on things that could cause more serious problems as a priority - that said, this is because we don't believe and yet to see this message in the fastlane failing a build, if this happens, please let us know!
