### ISSUE TITLE
Bundle step keep failing to install fastlane

### ISSUE THREAD

**Issue by ghadly** [bitrise-steplib/steps-fastlane#47]
We are facing a problem with the new release of fastlane step 2.5.0

Our Bitrise Xcode is 10.2 which is using the bundler 1.17.3 and ruby 2.5.3.

After updating bitrise step we get an error that `must user Bundler > 2.0` after updating the GemFile.lock to Bundle 2.0.2 we get another error 
`Install Fastlane with bundler
$ bundle "_2.0.2_" "install" "--jobs" "20" "--retry" "5"`.

**Comment by bitce** [comment]
Hi @georgehadly-marleyspoon could you please include the related build URLs?

**Comment by ghadly** [comment]
- update to Bundle 2.0 issue -> https://app.bitrise.io/build/ef85ca6bcb840e8e#?tab=log
- installing fastlane issue with bundler 2 -> https://app.bitrise.io/build/b735f6641ed6dda9#?tab=log

**Comment by bitce** [comment]
Thanks! 

Just so you know the the issue on the 2.4.0 can be workaround by placing this script before the fastlane step:

```
#!/bin/bash
set -ex
gem install bundler --force
```

For the issue with the new version, could you contact us on our on-site chat and send us your Gemfile.lock and Gemfile from your repo? It could also help to run this script in the failing build: https://github.com/rbenv/rbenv-installer/blob/master/bin/rbenv-doctor

**Comment by lpusok** [comment]
Hi @georgehadly-marleyspoon ,
This issue can happen if you have a custom value set for the GEM_HOME environment variable.

There is a new version of fastlane-install available (2.5.1):
https://github.com/bitrise-steplib/steps-fastlane/releases/tag/2.5.1 


Bundler is installed before executing `bundle install`, in case a Gemfile.lock is present. The specific version defined in the Gemfile.lock under `BUNDLED WITH` is installed and used to run the `bundle install` command.
The issues fixed include the error messages printed during build: ` rbenv: bundle: command not found` 
and `You must use Bundler 2 or greater with this lockfile.`

The fix is also available in:
cocoapods-install  (https://github.com/bitrise-steplib/steps-cocoapods-install/releases/tag/1.8.0)
deploy-to-itunesconnect-deliver (https://github.com/bitrise-steplib/steps-deploy-to-itunesconnect-deliver/releases/tag/2.16.0)

**Comment by ghadly** [comment]
Thanks for the update :)

**Comment by abdullah-s** [comment]
FYI - this also solves issue "Could not find 'bundler' (1.17.3)"
in " ios auto provision" step

**Comment by Roland-Bak** [comment]
Hey @abdullah-s , thanks for the info and for sharing! 😉
